### ISSUE TITLE
펀딩 페이지 - 펀딩 컴포넌트 구현

### ISSUE THREAD

**Issue by devkyoung2** [KakaoFunding/front-end#121]
### 작업 상세 내용

- [ ] 펀딩이 있을 경우
  - [ ] 상품 구현 #118 
  - [ ] 펀딩 진행률 구현 #119 
  - [ ] 펀딩 랭킹 리스트 구현 #120 
-  [ ] 펀딩이 없을 경우
   - [ ] default 컴포넌트 구현 #105 

## 참고할만한 자료
- 펀딩이 있을 경우
![image](https://github.com/KakaoFunding/front-end/assets/79066587/03e64643-96e0-44a5-80f5-b637749bcaff)
- 펀딩이 없을 경우
![image](https://github.com/KakaoFunding/front-end/assets/79066587/533b321d-a200-4a43-a823-9a5c16b32ac3)
